language: go

go:
  - 1.5.3
  - release

notifications:
  slack: mdfs:qbXCi4UykUI2w8vFBh4sw2X6

before_install:
  - cp .netrc ~
  - chmod 600 .netrc
  - mkdir -p $HOME/path/to/files/config
  - mkdir $HOME/path/to/files/stnode
  - mkdir $HOME/path/to/files/mdservice
  - cp $HOME/gopath/src/github.com/CPSSD/MDFS/storagenode/stnodeconf.json $HOME/path/to/files/config/stnodeconf.json
  - cp $HOME/gopath/src/github.com/CPSSD/MDFS/mdservice/mdserviceconf.json $HOME/path/to/files/config/mdserviceconf.json
  - cp $HOME/gopath/src/github.com/CPSSD/MDFS/test/* $HOME/path/to/files/
