language: go

go:
  - 1.5.3
  - release

notifications:
  slack: mdfs:qbXCi4UykUI2w8vFBh4sw2X6

before_install:
  - cp .netrc ~
  - chmod 600 .netrc
  - go run $HOME/gopath/src/github.com/CPSSD/MDFS/testing_files/testing_init.go
  - go run $HOME/gopath/src/github.com/CPSSD/MDFS/storagenode/config/stnode_init.go
  - go run $HOME/gopath/src/github.com/CPSSD/MDFS/mdservice/config/mdservice_init.go